pub use privet_crypto::constants::{
    CODE_VALIDITY_SECS, EXPORTER_LEN, MAX_CODE_ATTEMPTS, NONCE_LEN,
    PAIRING_BINDING_LABEL, PAIRING_CONFIRMATION_LABEL, PAIRING_CONTEXT_STRING,
};

pub const PAIRING_ACK_TIMEOUT_SECS: u64 = 30;
pub const PAIRING_MAX_RETRIES: u32 = 3;
pub const PAIRING_CONCURRENCY_PER_IP: u32 = 1;
pub const MAX_PAIRING_ATTEMPTS_PER_MIN: u32 = 5;
pub const IDENTITY_GC_STALE_DAYS: i64 = 180;
