[package]
name = "privet-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
privet-protocol = { path = "../privet-protocol" }
privet-crypto = { path = "../privet-crypto" }

# protocol
prost = "0.14"

# storage
rusqlite.workspace = true
dirs.workspace = true

# utils
hex.workspace = true
thiserror.workspace = true

# trace
tracing = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[build-dependencies]
prost-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
proptest.workspace = true
